## Examples of reshaping for the purposes of broadcasting

In [2]:
import numpy as np

### Example 1

Here we create an `ndarray` called `my_image`, that we would like to add another array to, called `my_filter`. 

In [3]:
my_image = np.array([[1, 1, 1, 0, 0, 0],
[1, 1 , 1, 0, 0, 0],
[1, 1 , 1, 0, 0, 0],
[0, 0 , 0, 0, 0, 0],
[0, 0 , 0, 0, 0, 0],
[0, 0 , 0, 0, 0, 0]])

In [4]:
my_image

array([[1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [5]:
my_image.shape

(6, 6)

Here we create the second `ndarray` that we'd like to use to add to `my_image`:

In [17]:
my_filter = np.array([[255, 255, 255],
       [255, 255, 255],
       [255, 255, 255]])
my_filter

array([[255, 255, 255],
       [255, 255, 255],
       [255, 255, 255]])

In [7]:
my_filter.shape

(3, 3)

If we try to directly add them, we get an error because they are not broadcastable:

In [18]:
my_image + my_filter

ValueError: operands could not be broadcast together with shapes (6,6) (3,3) 

Let's compare their shapes:

In [20]:
print(my_image.shape)
print(my_filter.shape)

(6, 6)
(3, 3)


Reading from right to left, we see the first problem is the 3 being different from the 6, let's reshape `my_image` so that the right-most dimension is 3:

In [22]:
my_image_reshaped = np.reshape(my_image, (12, 3))
my_image_reshaped

array([[1, 1, 1],
       [0, 0, 0],
       [1, 1, 1],
       [0, 0, 0],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Will this work? Not yet! We've fixed one dimension, but not the second-to-right one:

In [23]:
print(my_image_reshaped.shape)
print(my_filter.shape)

(12, 3)
(3, 3)


Let's take that 12 and reshape it to (4, 3) - note that this works because 12 = 4 * 3!

In [24]:
my_image_reshaped_again = np.reshape(my_image, (4, 3, 3))
my_image_reshaped_again

array([[[1, 1, 1],
        [0, 0, 0],
        [1, 1, 1]],

       [[0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [25]:
print(my_image_reshaped_again.shape)
print(my_filter.shape)

(4, 3, 3)
(3, 3)


Yes! This looks much better because reading from the right, the dimensions > 1 are the same! Let's try adding now!

In [38]:
my_image_plus_filter = my_image_reshaped_again + my_filter
my_image_plus_filter

array([[[256, 256, 256],
        [255, 255, 255],
        [256, 256, 256]],

       [[255, 255, 255],
        [256, 256, 256],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]])

We're not quite done though! Let's get `my_image_reshaped_again` back to it's original dimension:

In [39]:
np.reshape(my_image_plus_filter, (6, 6))

array([[256, 256, 256, 255, 255, 255],
       [256, 256, 256, 255, 255, 255],
       [256, 256, 256, 255, 255, 255],
       [255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255]])

### Example 2

What if we have these two 2D arrays that we want to add together?

In [30]:
array1 = np.array([[10, 10, 10, 10], 
                   [1, 1, 1, 1]])
array1

array([[10, 10, 10, 10],
       [ 1,  1,  1,  1]])

In [31]:
array2 = np.array([[2, 20], 
                   [2, 20],
                   [2, 20]])
array2

array([[ 2, 20],
       [ 2, 20],
       [ 2, 20]])

Let's check, are they broadcastable?

In [32]:
print(array1.shape)
print(array2.shape)

(2, 4)
(3, 2)


No! Let's reshape `array1` to set the right-most dimension to 2:

In [34]:
array1_reshaped = np.reshape(array1, (4, 2))
array1_reshaped

array([[10, 10],
       [10, 10],
       [ 1,  1],
       [ 1,  1]])

Will this work? Not quite...

In [35]:
print(array1_reshaped.shape)
print(array2.shape)

(4, 2)
(3, 2)


Let's try to work on that 4 in `array1_reshaped`:

In [36]:
array1_reshaped_again = np.reshape(array1, (4, 1, 2))
array1_reshaped_again

array([[[10, 10]],

       [[10, 10]],

       [[ 1,  1]],

       [[ 1,  1]]])

Will this work? Yes!

In [40]:
print(array1_reshaped_again.shape)
print(array2.shape)

(4, 1, 2)
(3, 2)


Let's add them now:

In [46]:
array1_plus_array2 = array1_reshaped_again + array2
array1_plus_array2

array([[[12, 30],
        [12, 30],
        [12, 30]],

       [[12, 30],
        [12, 30],
        [12, 30]],

       [[ 3, 21],
        [ 3, 21],
        [ 3, 21]],

       [[ 3, 21],
        [ 3, 21],
        [ 3, 21]]])

In this example, we cannot reshape the resultant array back into the same shape as either of the originals without losing data.