# Worksheet 5 - NumPy

In [1]:
import numpy as np

### Exercise 1
rubric={autograde:1}

Create the following array and save it as a variable named `ex1`:

```python
array([[1, 2],
       [3, 4],
       [5, 6]])
```

In [2]:
ex1 = np.arange(1, 7).reshape((3, 2))  # SOLUTION

In [3]:
# TEST
assert type(ex1) == np.ndarray, "ex1 should be a numpy array"

In [4]:
# TEST
assert ex1.shape == (3, 2), "ex1 should have shape (3, 2)"

In [5]:
# TEST
assert ex1[0][0] == 1

In [6]:
# TEST
assert ex1[0][1] == 2

In [7]:
# TEST
assert ex1[2][0] == 5

In [8]:
# TEST
assert ex1[2][1] == 6

### Exercise 2

Create a 1D array of 5 zeros and save it as a variable named `ex2`:

In [9]:
ex2 = np.zeros(5) # SOLUTION

In [10]:
assert type(ex2) == np.ndarray, "ex2 should be a numpy array"
assert ex2.shape == (5,), "ex2 should be a 1D array of length 5"
assert np.array_equal(ex2, np.array([0., 0., 0., 0., 0.])), "q2_1 should be a 1D array of zeros"

### Exercise 3

Create a 1D array of 10 and save it as a variable named `ex3`:

In [11]:
ex3 = np.ones(10) # SOLUTION

In [12]:
assert type(ex3) == np.ndarray, "ex3 should be a numpy array"
assert ex3.shape == (10,), "ex3 should be a 1D array of length 10"
assert np.array_equal(ex3, np.array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])), "q2_2 should be a 1D array of ones"

### Exercise 4

Create a 1D array of five numbers, each having the value of 3.141, and save it as a variable named `ex4`:

In [13]:
ex4 = np.full(5, 3.141) # SOLUTION

In [14]:
assert type(ex4) == np.ndarray, "ex4 should be a numpy array"
assert ex4.shape == (5,), "ex4 should be a 1D array of length 5"
assert np.array_equal(ex4, np.array([3.141, 3.141, 3.141, 3.141, 3.141])), "ex4 should be a 1D array of 3.141s"

### Exercise 5

Create a 1D array of the integers 1 to 20 and save it as a variable named `ex5`:

In [15]:
ex5 = np.array(range(1,21)) # SOLUTION

In [16]:
assert type(ex5) == np.ndarray, "ex5 should be a numpy array"
assert ex5.shape == (20,), "ex5 should be a 1D array of length 20"
assert np.array_equal(ex5, np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]))

### Exercise 6

Create a 5 x 5 matrix of ones with a dtype `int` and save it as a variable named `ex6`:

In [17]:
ex6 = np.ones((5, 5), dtype=int) # SOLUTION

In [18]:
assert type(ex6) == np.ndarray, "ex6 should be a numpy array"
assert ex6.shape == (5, 5), "ex6 should be a 2D array of shape (5, 5)"
assert np.array_equal(ex6, np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])), "ex6 should be a 2D array of ones"

### Exercise 7

Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`) and save it as a variable named `ex7`:

> Hint: To ensure the code reproducibility, set the random seed = 42 using the `np.random.seed()` function.

In [19]:
# set your seed to 42 for reproducibility
ex7 = np.random.randn(3, 3, 3) # SOLUTION

In [20]:
assert type(ex7) == np.ndarray, "ex7 should be a numpy array"
assert ex7.shape == (3, 3, 3), "ex7 should be a 3D array of shape (3, 3, 3)"

### Exercise 8

Reshape the above array (`ex7`) into shape (27,) and save it as a variable named `ex8`:

In [21]:
ex8 = ex7.reshape(27) # SOLUTION

In [22]:
assert type(ex8) == np.ndarray, "ex8 should be a numpy array"
assert ex8.shape == (27,), "ex8 should be a 1D array of length 27"

### Exercise 9

Reshape the following `arr1` into shape `(6, 1)` and save it as a variable named `ex9`:

In [23]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
ex9 = arr1.reshape((6, 1))  # SOLUTION

In [25]:
# TEST
assert type(ex9) == np.ndarray, "ex9 should be a numpy array"

In [26]:
# TEST
assert ex9.shape == (6, 1), "ex9 should have shape (6, 1)"

In [27]:
# TEST
assert ex9[0] == 1

In [28]:
# TEST
assert ex9[-1] == 6

### Exercise 10

Create a `(6, 6)` array by multiplying the following `arr2` by itself (**hint**: transpose the array to leverage broadcasting here). The first element (top left corner) should be 1, and the last element (bottom right corner) should be 36. Save it as a variable named `ex10`.

In [29]:
arr2 = np.arange(1, 7)[np.newaxis, :] # np.newaxis is an alias for None
arr2

array([[1, 2, 3, 4, 5, 6]])

In [32]:
ex10 = arr2 * np.transpose(arr2)  # SOLUTION
ex10

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [31]:
# TEST
assert type(ex10) == np.ndarray, "ex10 should be a numpy array"

In [32]:
# TEST
assert ex10.shape == (6, 6), "ex10 should have shape (6, 6)"

In [33]:
# TEST
assert ex10[0, 0] == 1

In [34]:
# TEST
assert ex10[-1, -1] == 36

### Exercise 11

"Center" the following `arr3` by subtracting the mean from every element, then flatten it to shape `(20,)` and use `numpy.sort` to sort it in descending order. Save it as a variable named `ex11`.

In [35]:
arr3 = np.arange(1, 21).reshape(4, 5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
ex11 = np.sort(arr3 - arr3.mean()).flatten()[::-1]  # SOLUTION

In [37]:
# TEST
assert type(ex11) == np.ndarray, "ex11 should be a numpy array"

In [38]:
# TEST
assert ex11.shape == (20,), "ex11 should have shape (20,)"

In [39]:
# TEST
assert ex11[0] == 9.5

In [40]:
# TEST
assert ex11[-1] == -9.5

In [41]:
# TEST
assert ex11.sum() == 0

Congratulations! You are done the worksheet!!! Pat yourself on the back and submit your worksheet to Gradescope!